// flow-typed signature: ca47c3493b840984644667397c3ca7a5
// flow-typed version: <<STUB>>/glitch-canvas_v^1.1.8/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glitch-canvas'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glitch-canvas' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'glitch-canvas/build' {
  declare module.exports: any;
}

declare module 'glitch-canvas/dist/glitch-canvas-browser-with-polyfills' {
  declare module.exports: any;
}

declare module 'glitch-canvas/dist/glitch-canvas-browser-with-polyfills.min' {
  declare module.exports: any;
}

declare module 'glitch-canvas/dist/glitch-canvas-browser.es6' {
  declare module.exports: any;
}

declare module 'glitch-canvas/dist/glitch-canvas-browser.es6.min' {
  declare module.exports: any;
}

declare module 'glitch-canvas/dist/glitch-canvas-browser.es6.umd' {
  declare module.exports: any;
}

declare module 'glitch-canvas/dist/glitch-canvas-browser.es6.umd.min' {
  declare module.exports: any;
}

declare module 'glitch-canvas/dist/glitch-canvas-browser' {
  declare module.exports: any;
}

declare module 'glitch-canvas/dist/glitch-canvas-browser.min' {
  declare module.exports: any;
}

declare module 'glitch-canvas/dist/glitch-canvas-node' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/browser' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/glitch/base64Map' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/glitch/base64ToByteArray' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/glitch/browser/imageDataToBase64' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/glitch/byteArrayToBase64' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/glitch/glitchByteArray' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/glitch/glitchImageData' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/glitch/jpgHeaderLength' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/glitch/node/imageDataToBase64' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/input/browser/fromImage' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/input/defaultParams' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/input/node/fromBuffer' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/input/node/fromStream' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/input/sanitizeInput' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/output/browser/toImage' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/output/node/toBuffer' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/output/node/toJPGStream' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/output/node/toPNGStream' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/output/toImageData' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/util/browser' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/util/canvas' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/util/canvasFromImage' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/util/clamp' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/util/clone' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/util/copyImageData' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/util/getImageSize' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/util/isImageData' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/util/loadBase64Image' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/util/node-canvas' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/util/object-assign' {
  declare module.exports: any;
}

declare module 'glitch-canvas/src/workers/glitchWorker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'glitch-canvas/build.js' {
  declare module.exports: $Exports<'glitch-canvas/build'>;
}
declare module 'glitch-canvas/dist/glitch-canvas-browser-with-polyfills.js' {
  declare module.exports: $Exports<'glitch-canvas/dist/glitch-canvas-browser-with-polyfills'>;
}
declare module 'glitch-canvas/dist/glitch-canvas-browser-with-polyfills.min.js' {
  declare module.exports: $Exports<'glitch-canvas/dist/glitch-canvas-browser-with-polyfills.min'>;
}
declare module 'glitch-canvas/dist/glitch-canvas-browser.es6.js' {
  declare module.exports: $Exports<'glitch-canvas/dist/glitch-canvas-browser.es6'>;
}
declare module 'glitch-canvas/dist/glitch-canvas-browser.es6.min.js' {
  declare module.exports: $Exports<'glitch-canvas/dist/glitch-canvas-browser.es6.min'>;
}
declare module 'glitch-canvas/dist/glitch-canvas-browser.es6.umd.js' {
  declare module.exports: $Exports<'glitch-canvas/dist/glitch-canvas-browser.es6.umd'>;
}
declare module 'glitch-canvas/dist/glitch-canvas-browser.es6.umd.min.js' {
  declare module.exports: $Exports<'glitch-canvas/dist/glitch-canvas-browser.es6.umd.min'>;
}
declare module 'glitch-canvas/dist/glitch-canvas-browser.js' {
  declare module.exports: $Exports<'glitch-canvas/dist/glitch-canvas-browser'>;
}
declare module 'glitch-canvas/dist/glitch-canvas-browser.min.js' {
  declare module.exports: $Exports<'glitch-canvas/dist/glitch-canvas-browser.min'>;
}
declare module 'glitch-canvas/dist/glitch-canvas-node.js' {
  declare module.exports: $Exports<'glitch-canvas/dist/glitch-canvas-node'>;
}
declare module 'glitch-canvas/src/browser.js' {
  declare module.exports: $Exports<'glitch-canvas/src/browser'>;
}
declare module 'glitch-canvas/src/glitch/base64Map.js' {
  declare module.exports: $Exports<'glitch-canvas/src/glitch/base64Map'>;
}
declare module 'glitch-canvas/src/glitch/base64ToByteArray.js' {
  declare module.exports: $Exports<'glitch-canvas/src/glitch/base64ToByteArray'>;
}
declare module 'glitch-canvas/src/glitch/browser/imageDataToBase64.js' {
  declare module.exports: $Exports<'glitch-canvas/src/glitch/browser/imageDataToBase64'>;
}
declare module 'glitch-canvas/src/glitch/byteArrayToBase64.js' {
  declare module.exports: $Exports<'glitch-canvas/src/glitch/byteArrayToBase64'>;
}
declare module 'glitch-canvas/src/glitch/glitchByteArray.js' {
  declare module.exports: $Exports<'glitch-canvas/src/glitch/glitchByteArray'>;
}
declare module 'glitch-canvas/src/glitch/glitchImageData.js' {
  declare module.exports: $Exports<'glitch-canvas/src/glitch/glitchImageData'>;
}
declare module 'glitch-canvas/src/glitch/jpgHeaderLength.js' {
  declare module.exports: $Exports<'glitch-canvas/src/glitch/jpgHeaderLength'>;
}
declare module 'glitch-canvas/src/glitch/node/imageDataToBase64.js' {
  declare module.exports: $Exports<'glitch-canvas/src/glitch/node/imageDataToBase64'>;
}
declare module 'glitch-canvas/src/index' {
  declare module.exports: $Exports<'glitch-canvas/src'>;
}
declare module 'glitch-canvas/src/index.js' {
  declare module.exports: $Exports<'glitch-canvas/src'>;
}
declare module 'glitch-canvas/src/input/browser/fromImage.js' {
  declare module.exports: $Exports<'glitch-canvas/src/input/browser/fromImage'>;
}
declare module 'glitch-canvas/src/input/defaultParams.js' {
  declare module.exports: $Exports<'glitch-canvas/src/input/defaultParams'>;
}
declare module 'glitch-canvas/src/input/node/fromBuffer.js' {
  declare module.exports: $Exports<'glitch-canvas/src/input/node/fromBuffer'>;
}
declare module 'glitch-canvas/src/input/node/fromStream.js' {
  declare module.exports: $Exports<'glitch-canvas/src/input/node/fromStream'>;
}
declare module 'glitch-canvas/src/input/sanitizeInput.js' {
  declare module.exports: $Exports<'glitch-canvas/src/input/sanitizeInput'>;
}
declare module 'glitch-canvas/src/output/browser/toImage.js' {
  declare module.exports: $Exports<'glitch-canvas/src/output/browser/toImage'>;
}
declare module 'glitch-canvas/src/output/node/toBuffer.js' {
  declare module.exports: $Exports<'glitch-canvas/src/output/node/toBuffer'>;
}
declare module 'glitch-canvas/src/output/node/toJPGStream.js' {
  declare module.exports: $Exports<'glitch-canvas/src/output/node/toJPGStream'>;
}
declare module 'glitch-canvas/src/output/node/toPNGStream.js' {
  declare module.exports: $Exports<'glitch-canvas/src/output/node/toPNGStream'>;
}
declare module 'glitch-canvas/src/output/toImageData.js' {
  declare module.exports: $Exports<'glitch-canvas/src/output/toImageData'>;
}
declare module 'glitch-canvas/src/util/browser.js' {
  declare module.exports: $Exports<'glitch-canvas/src/util/browser'>;
}
declare module 'glitch-canvas/src/util/canvas.js' {
  declare module.exports: $Exports<'glitch-canvas/src/util/canvas'>;
}
declare module 'glitch-canvas/src/util/canvasFromImage.js' {
  declare module.exports: $Exports<'glitch-canvas/src/util/canvasFromImage'>;
}
declare module 'glitch-canvas/src/util/clamp.js' {
  declare module.exports: $Exports<'glitch-canvas/src/util/clamp'>;
}
declare module 'glitch-canvas/src/util/clone.js' {
  declare module.exports: $Exports<'glitch-canvas/src/util/clone'>;
}
declare module 'glitch-canvas/src/util/copyImageData.js' {
  declare module.exports: $Exports<'glitch-canvas/src/util/copyImageData'>;
}
declare module 'glitch-canvas/src/util/getImageSize.js' {
  declare module.exports: $Exports<'glitch-canvas/src/util/getImageSize'>;
}
declare module 'glitch-canvas/src/util/isImageData.js' {
  declare module.exports: $Exports<'glitch-canvas/src/util/isImageData'>;
}
declare module 'glitch-canvas/src/util/loadBase64Image.js' {
  declare module.exports: $Exports<'glitch-canvas/src/util/loadBase64Image'>;
}
declare module 'glitch-canvas/src/util/node-canvas.js' {
  declare module.exports: $Exports<'glitch-canvas/src/util/node-canvas'>;
}
declare module 'glitch-canvas/src/util/object-assign.js' {
  declare module.exports: $Exports<'glitch-canvas/src/util/object-assign'>;
}
declare module 'glitch-canvas/src/workers/glitchWorker.js' {
  declare module.exports: $Exports<'glitch-canvas/src/workers/glitchWorker'>;
}
