// flow-typed signature: d1d093d6c0348433d9eb80f427eddee9
// flow-typed version: <<STUB>>/tui-image-editor_v^3.14.3/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tui-image-editor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tui-image-editor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tui-image-editor/dist/tui-image-editor' {
  declare module.exports: any;
}

declare module 'tui-image-editor/dist/tui-image-editor.min' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/action' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/command/addIcon' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/command/addImageObject' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/command/addObject' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/command/addShape' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/command/addText' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/command/applyFilter' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/command/changeIconColor' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/command/changeSelection' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/command/changeShape' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/command/changeText' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/command/changeTextStyle' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/command/clearObjects' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/command/flip' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/command/loadImage' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/command/removeFilter' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/command/removeObject' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/command/resizeCanvasDimension' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/command/rotate' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/command/setObjectPosition' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/command/setObjectProperties' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/component/cropper' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/component/filter' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/component/flip' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/component/freeDrawing' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/component/icon' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/component/imageLoader' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/component/line' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/component/rotation' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/component/shape' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/component/text' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/component/zoom' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/consts' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/drawingMode/cropper' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/drawingMode/freeDrawing' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/drawingMode/icon' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/drawingMode/lineDrawing' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/drawingMode/shape' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/drawingMode/text' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/drawingMode/zoom' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/extension/arrowLine' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/extension/blur' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/extension/colorFilter' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/extension/cropzone' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/extension/emboss' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/extension/mask' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/extension/sharpen' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/factory/command' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/factory/errorMessage' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/graphics' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/helper/imagetracer' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/helper/selectionModifyHelper' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/helper/shapeFilterFillHelper' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/helper/shapeResizeHelper' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/imageEditor' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/interface/command' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/interface/component' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/interface/drawingMode' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/invoker' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/polyfill' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/crop' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/draw' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/filter' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/flip' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/history' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/icon' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/locale/locale' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/mask' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/panelMenu' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/rotate' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/shape' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/submenuBase' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/template/controls' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/template/mainContainer' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/template/style' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/template/submenu/crop' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/template/submenu/draw' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/template/submenu/filter' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/template/submenu/flip' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/template/submenu/history' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/template/submenu/icon' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/template/submenu/mask' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/template/submenu/rotate' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/template/submenu/shape' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/template/submenu/text' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/template/submenu/zoom' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/text' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/theme/standard' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/theme/theme' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/tools/colorpicker' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/ui/tools/range' {
  declare module.exports: any;
}

declare module 'tui-image-editor/src/js/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tui-image-editor/dist/tui-image-editor.js' {
  declare module.exports: $Exports<'tui-image-editor/dist/tui-image-editor'>;
}
declare module 'tui-image-editor/dist/tui-image-editor.min.js' {
  declare module.exports: $Exports<'tui-image-editor/dist/tui-image-editor.min'>;
}
declare module 'tui-image-editor/src/index' {
  declare module.exports: $Exports<'tui-image-editor/src'>;
}
declare module 'tui-image-editor/src/index.js' {
  declare module.exports: $Exports<'tui-image-editor/src'>;
}
declare module 'tui-image-editor/src/js/action.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/action'>;
}
declare module 'tui-image-editor/src/js/command/addIcon.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/command/addIcon'>;
}
declare module 'tui-image-editor/src/js/command/addImageObject.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/command/addImageObject'>;
}
declare module 'tui-image-editor/src/js/command/addObject.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/command/addObject'>;
}
declare module 'tui-image-editor/src/js/command/addShape.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/command/addShape'>;
}
declare module 'tui-image-editor/src/js/command/addText.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/command/addText'>;
}
declare module 'tui-image-editor/src/js/command/applyFilter.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/command/applyFilter'>;
}
declare module 'tui-image-editor/src/js/command/changeIconColor.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/command/changeIconColor'>;
}
declare module 'tui-image-editor/src/js/command/changeSelection.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/command/changeSelection'>;
}
declare module 'tui-image-editor/src/js/command/changeShape.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/command/changeShape'>;
}
declare module 'tui-image-editor/src/js/command/changeText.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/command/changeText'>;
}
declare module 'tui-image-editor/src/js/command/changeTextStyle.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/command/changeTextStyle'>;
}
declare module 'tui-image-editor/src/js/command/clearObjects.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/command/clearObjects'>;
}
declare module 'tui-image-editor/src/js/command/flip.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/command/flip'>;
}
declare module 'tui-image-editor/src/js/command/loadImage.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/command/loadImage'>;
}
declare module 'tui-image-editor/src/js/command/removeFilter.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/command/removeFilter'>;
}
declare module 'tui-image-editor/src/js/command/removeObject.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/command/removeObject'>;
}
declare module 'tui-image-editor/src/js/command/resizeCanvasDimension.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/command/resizeCanvasDimension'>;
}
declare module 'tui-image-editor/src/js/command/rotate.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/command/rotate'>;
}
declare module 'tui-image-editor/src/js/command/setObjectPosition.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/command/setObjectPosition'>;
}
declare module 'tui-image-editor/src/js/command/setObjectProperties.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/command/setObjectProperties'>;
}
declare module 'tui-image-editor/src/js/component/cropper.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/component/cropper'>;
}
declare module 'tui-image-editor/src/js/component/filter.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/component/filter'>;
}
declare module 'tui-image-editor/src/js/component/flip.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/component/flip'>;
}
declare module 'tui-image-editor/src/js/component/freeDrawing.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/component/freeDrawing'>;
}
declare module 'tui-image-editor/src/js/component/icon.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/component/icon'>;
}
declare module 'tui-image-editor/src/js/component/imageLoader.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/component/imageLoader'>;
}
declare module 'tui-image-editor/src/js/component/line.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/component/line'>;
}
declare module 'tui-image-editor/src/js/component/rotation.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/component/rotation'>;
}
declare module 'tui-image-editor/src/js/component/shape.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/component/shape'>;
}
declare module 'tui-image-editor/src/js/component/text.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/component/text'>;
}
declare module 'tui-image-editor/src/js/component/zoom.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/component/zoom'>;
}
declare module 'tui-image-editor/src/js/consts.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/consts'>;
}
declare module 'tui-image-editor/src/js/drawingMode/cropper.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/drawingMode/cropper'>;
}
declare module 'tui-image-editor/src/js/drawingMode/freeDrawing.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/drawingMode/freeDrawing'>;
}
declare module 'tui-image-editor/src/js/drawingMode/icon.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/drawingMode/icon'>;
}
declare module 'tui-image-editor/src/js/drawingMode/lineDrawing.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/drawingMode/lineDrawing'>;
}
declare module 'tui-image-editor/src/js/drawingMode/shape.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/drawingMode/shape'>;
}
declare module 'tui-image-editor/src/js/drawingMode/text.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/drawingMode/text'>;
}
declare module 'tui-image-editor/src/js/drawingMode/zoom.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/drawingMode/zoom'>;
}
declare module 'tui-image-editor/src/js/extension/arrowLine.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/extension/arrowLine'>;
}
declare module 'tui-image-editor/src/js/extension/blur.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/extension/blur'>;
}
declare module 'tui-image-editor/src/js/extension/colorFilter.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/extension/colorFilter'>;
}
declare module 'tui-image-editor/src/js/extension/cropzone.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/extension/cropzone'>;
}
declare module 'tui-image-editor/src/js/extension/emboss.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/extension/emboss'>;
}
declare module 'tui-image-editor/src/js/extension/mask.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/extension/mask'>;
}
declare module 'tui-image-editor/src/js/extension/sharpen.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/extension/sharpen'>;
}
declare module 'tui-image-editor/src/js/factory/command.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/factory/command'>;
}
declare module 'tui-image-editor/src/js/factory/errorMessage.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/factory/errorMessage'>;
}
declare module 'tui-image-editor/src/js/graphics.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/graphics'>;
}
declare module 'tui-image-editor/src/js/helper/imagetracer.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/helper/imagetracer'>;
}
declare module 'tui-image-editor/src/js/helper/selectionModifyHelper.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/helper/selectionModifyHelper'>;
}
declare module 'tui-image-editor/src/js/helper/shapeFilterFillHelper.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/helper/shapeFilterFillHelper'>;
}
declare module 'tui-image-editor/src/js/helper/shapeResizeHelper.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/helper/shapeResizeHelper'>;
}
declare module 'tui-image-editor/src/js/imageEditor.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/imageEditor'>;
}
declare module 'tui-image-editor/src/js/interface/command.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/interface/command'>;
}
declare module 'tui-image-editor/src/js/interface/component.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/interface/component'>;
}
declare module 'tui-image-editor/src/js/interface/drawingMode.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/interface/drawingMode'>;
}
declare module 'tui-image-editor/src/js/invoker.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/invoker'>;
}
declare module 'tui-image-editor/src/js/polyfill.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/polyfill'>;
}
declare module 'tui-image-editor/src/js/ui.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui'>;
}
declare module 'tui-image-editor/src/js/ui/crop.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/crop'>;
}
declare module 'tui-image-editor/src/js/ui/draw.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/draw'>;
}
declare module 'tui-image-editor/src/js/ui/filter.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/filter'>;
}
declare module 'tui-image-editor/src/js/ui/flip.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/flip'>;
}
declare module 'tui-image-editor/src/js/ui/history.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/history'>;
}
declare module 'tui-image-editor/src/js/ui/icon.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/icon'>;
}
declare module 'tui-image-editor/src/js/ui/locale/locale.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/locale/locale'>;
}
declare module 'tui-image-editor/src/js/ui/mask.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/mask'>;
}
declare module 'tui-image-editor/src/js/ui/panelMenu.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/panelMenu'>;
}
declare module 'tui-image-editor/src/js/ui/rotate.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/rotate'>;
}
declare module 'tui-image-editor/src/js/ui/shape.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/shape'>;
}
declare module 'tui-image-editor/src/js/ui/submenuBase.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/submenuBase'>;
}
declare module 'tui-image-editor/src/js/ui/template/controls.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/template/controls'>;
}
declare module 'tui-image-editor/src/js/ui/template/mainContainer.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/template/mainContainer'>;
}
declare module 'tui-image-editor/src/js/ui/template/style.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/template/style'>;
}
declare module 'tui-image-editor/src/js/ui/template/submenu/crop.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/template/submenu/crop'>;
}
declare module 'tui-image-editor/src/js/ui/template/submenu/draw.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/template/submenu/draw'>;
}
declare module 'tui-image-editor/src/js/ui/template/submenu/filter.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/template/submenu/filter'>;
}
declare module 'tui-image-editor/src/js/ui/template/submenu/flip.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/template/submenu/flip'>;
}
declare module 'tui-image-editor/src/js/ui/template/submenu/history.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/template/submenu/history'>;
}
declare module 'tui-image-editor/src/js/ui/template/submenu/icon.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/template/submenu/icon'>;
}
declare module 'tui-image-editor/src/js/ui/template/submenu/mask.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/template/submenu/mask'>;
}
declare module 'tui-image-editor/src/js/ui/template/submenu/rotate.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/template/submenu/rotate'>;
}
declare module 'tui-image-editor/src/js/ui/template/submenu/shape.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/template/submenu/shape'>;
}
declare module 'tui-image-editor/src/js/ui/template/submenu/text.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/template/submenu/text'>;
}
declare module 'tui-image-editor/src/js/ui/template/submenu/zoom.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/template/submenu/zoom'>;
}
declare module 'tui-image-editor/src/js/ui/text.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/text'>;
}
declare module 'tui-image-editor/src/js/ui/theme/standard.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/theme/standard'>;
}
declare module 'tui-image-editor/src/js/ui/theme/theme.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/theme/theme'>;
}
declare module 'tui-image-editor/src/js/ui/tools/colorpicker.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/tools/colorpicker'>;
}
declare module 'tui-image-editor/src/js/ui/tools/range.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/ui/tools/range'>;
}
declare module 'tui-image-editor/src/js/util.js' {
  declare module.exports: $Exports<'tui-image-editor/src/js/util'>;
}
