import avatarPlaceholder from '../../../common/assets/images/avatar-placeholder.png'

const comments = [
  {
    id: 1,
    avatar: avatarPlaceholder,
    name: 'Reymundo',
    when: '19h ago',
    comment: 'Awesome! 😍',
    commentedOn: 'Unity Dashboard kit.',
    likes: 23,
  },
  {
    id: 2,
    avatar: avatarPlaceholder,
    name: 'Reymundo',
    when: '19h ago',
    comment: 'Awesome! 😍',
    commentedOn: 'Unity Dashboard kit.',
    likes: 2,
  },
  {
    id: 3,
    avatar: avatarPlaceholder,
    name: 'Reymundo',
    when: '19h ago',
    comment: 'Awesome! 😍',
    commentedOn: 'Unity Dashboard kit.',
    likes: 3,
  },
  {
    id: 4,
    avatar: avatarPlaceholder,
    name: 'Reymundo',
    when: '19h ago',
    comment: 'Awesome! 😍',
    commentedOn: 'Unity Dashboard kit.',
    likes: 4,
  },
  {
    id: 5,
    avatar: avatarPlaceholder,
    name: 'Reymundo',
    when: '19h ago',
    comment: 'Awesome! 😍',
    commentedOn: 'Unity Dashboard kit.',
    likes: 23,
  },
  {
    id: 6,
    avatar: avatarPlaceholder,
    name: 'Reymundo',
    when: '19h ago',
    comment: 'Awesome! 😍',
    commentedOn: 'Unity Dashboard kit.',
    likes: 5,
  },
  {
    id: 7,
    avatar: avatarPlaceholder,
    name: 'Reymundo',
    when: '19h ago',
    comment: 'Awesome! 😍',
    commentedOn: 'Unity Dashboard kit.',
    likes: 6,
  },
  {
    id: 8,
    avatar: avatarPlaceholder,
    name: 'Reymundo',
    when: '19h ago',
    comment: 'Awesome! 😍',
    commentedOn: 'Unity Dashboard kit.',
    likes: 33,
  },
  {
    id: 9,
    avatar: avatarPlaceholder,
    name: 'Reymundo',
    when: '19h ago',
    comment: 'Awesome! 😍',
    commentedOn: 'Unity Dashboard kit.',
    likes: 4,
  },
  {
    id: 10,
    avatar: avatarPlaceholder,
    name: 'Reymundo',
    when: '19h ago',
    comment: 'Awesome! 😍',
    commentedOn: 'Unity Dashboard kit.',
    likes: 7,
  },
  {
    id: 11,
    avatar: avatarPlaceholder,
    name: 'Reymundo',
    when: '19h ago',
    comment: 'Awesome! 😍',
    commentedOn: 'Unity Dashboard kit.',
    likes: 23,
  },
]

export default comments
