export const pastelTableNames = {
  statisticinfo: 'statisticinfo',
  networkinfo: 'networkinfo',
  nettotals: 'nettotals',
  mempoolinfo: 'mempoolinfo',
  rawmempoolinfo: 'rawmempoolinfo',
  mininginfo: 'mininginfo',
  blockinfo: 'blockinfo',
  rawtransaction: 'rawtransaction',
  transaction_tbl: 'transaction_tbl',
  txoutsetinfo: 'txoutsetinfo',
  chaintips: 'chaintips',
  blocksubsidy: 'blocksubsidy',
  walletinfo: 'walletinfo',
  listreceivedbyaddress: 'listreceivedbyaddress',
  listtransactions: 'listtransactions',
  listunspent: 'listunspent',
  totalbalance: 'totalbalance',
  listaddresses: 'listaddresses',
}

export const pastelChartFields = [
  { name: 'Difficulty', routeName: '/difficultyovertime' },
  { name: 'Hashrate', routeName: '/hashrateovertime' },
  { name: 'PSL Price', routeName: '/priceovertime' },
  { name: 'Rawtransaction', routeName: '/rawtransaction' },
  { name: 'Txoutsetinfo', routeName: '/txoutsetinfo' },
  { name: 'Walletinfo', routeName: '/walletinfo' },
  { name: 'RawMempool', routeName: '/rawmempoolovertime' },
  { name: 'MempoolSize', routeName: '/mempoolsizeovertime' },
  { name: 'Miners Revenue', routeName: '/minersrevenue' },
]
