export const pastelTableNames = {
  statisticinfo: 'statisticInfo',
  networkinfo: 'networkInfo',
  nettotals: 'netTotals',
  mempoolinfo: 'memPoolInfo',
  rawmempoolinfo: 'rawMemPoolInfo',
  mininginfo: 'miningInfo',
  blockinfo: 'blockInfo',
  rawtransaction: 'rawTransaction',
  transaction_tbl: 'transactionTbl',
  txoutsetinfo: 'txOutSetInfo',
  chaintips: 'chainTips',
  blocksubsidy: 'blockSubsidy',
  walletinfo: 'walletInfo',
  listreceivedbyaddress: 'listReceivedByAddress',
  listtransactions: 'listTransactions',
  listunspent: 'listUnspent',
  totalbalance: 'totalBalance',
  listaddresses: 'listAddresses',
  pslprice: 'priceInfo',
}
